# Generated by Django 5.0.6 on 2024-06-29 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='category',
            field=models.CharField(choices=[('userstory', 'User Story'), ('technical', 'Technical Task')], default='userstory', max_length=20),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='low', max_length=50),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('todo', 'To do'), ('progress', 'In progress'), ('feedback', 'Await feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='subtask',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
