# Generated by Django 5.0.6 on 2024-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_user_email_user_first_name_user_last_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
