# Generated by Django 5.0.6 on 2024-06-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='JoinUser',
        ),
    ]
