# Generated by Django 5.0.6 on 2024-07-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_remove_todoitem_subtask_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='subtask',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
