# Generated by Django 5.0.6 on 2024-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_todoitem_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='subtask',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='subtask_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='subtask_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
