# Generated by Django 5.0.6 on 2024-07-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_remove_todoitem_subtask_todoitem_subtask_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='subtask_check',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='subtask_text',
        ),
    ]
