# Generated by Django 5.0.6 on 2024-07-02 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_alter_todoitem_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='todo_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
