# Generated by Django 5.0.6 on 2024-07-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_alter_todoitem_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='todo_users', to='todos.joinuser'),
        ),
    ]
