# Generated by Django 5.0.6 on 2024-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_alter_todoitem_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinuser',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
