# Generated by Django 5.0.6 on 2024-07-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_joinuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='last_name',
        ),
    ]
