# Generated by Django 5.0.6 on 2024-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0018_alter_joinuser_options_alter_joinuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='joinuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
