# Generated by Django 5.0.6 on 2024-07-04 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_alter_joinuser_options_alter_joinuser_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='todo_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
