# Generated by Django 5.0.6 on 2024-07-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0021_remove_joinuser_phone_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
