# Generated by Django 5.0.6 on 2024-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0022_joinuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
