# Generated by Django 5.0.6 on 2024-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0023_customuser_email_customuser_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinUser',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='todo_users', to='todos.customuser'),
        ),
    ]
