# Generated by Django 5.0.6 on 2024-07-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0024_delete_joinuser_alter_todoitem_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user',
            new_name='username',
        ),
    ]
