# Generated by Django 5.0.6 on 2024-07-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0025_rename_user_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='user',
        ),
    ]
